# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # config.vm.box = "centos/7"
  config.vm.box = "boxcutter/centos72"
  config.vbguest.auto_update = false
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.40.40"
#  host_config.ssh.username = "vagrant"
#host_config.ssh.password = "vagrant"
#host_config.ssh.insert_key = "false"
 config.vm.provision "shell", inline: <<-SHELL
    # yum update
   SHELL
   config.vm.provision "ansible_local" do |ansible|
   ansible.playbook = "mongo.yml"
   #ansible.inventory_path = "/vagrant/inventory/mongo"
   #ansible.limit = "all"
  # ansible.raw_arguments = [ '--connection=local' ]
  end
end
